### PR TITLE
Limit request methods

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Comment by petrdvorak** [comment]
@banterCZ This is all very nice but again, I have no idea why we work on it now...

**Review by petrdvorak — CHANGES_REQUESTED** [review]
- Have you tested the change with complete stack integration?
- Does the client library need updates accordingly?

**Review by petrdvorak — APPROVED** [review]
Looks OK - did the testing.

**Comment by banterCZ** [comment]
> * Does the client library need updates accordingly?

Only admin controllers affected. I do not see any need to update client library. JSP stay all the same.

**Comment by petrdvorak** [comment]
Merging.

**Pull request merged**
