### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Review by romanstrobl — APPROVED** [review]
Looks OK.

**Review by petrdvorak — APPROVED** [review]
Looks good.

**Comment by banterCZ** [comment]
It was suggested by @petrdvorak to move the file to https://github.com/wultra/.github

> GitHub will use and display default files for any repository owned by the account that does not have its own file of that type.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files

**Comment by banterCZ** [comment]
See https://github.com/wultra/.github/pull/1

**Comment by banterCZ** [comment]
Let's use only the file at https://github.com/wultra/.github

**Pull request closed without merging**
