### PR TITLE
Fix #1257: Database initialization using Liquibase fails

### LINKED ISSUE #1257: Database initialization using Liquibase fails
Error:

```[2024-01-17 15:08:31] [42P07] ERROR: relation "pa_operation_application" already exists```

Reason:

```
 <changeSet id="24" logicalFilePath="powerauth-java-server/1.4.x/20230322-init-db.xml" author="Lubos Racansky">
        <preConditions onFail="MARK_RAN">
            <not>
                <tableExists tableName="pa_operation_application"/>
            </not>
        </preConditions>
        <comment>Create a new table pa_operation_application</comment>
        <createTable tableName="pa_operation_application">
            <column name="application_id" type="bigint">
                <constraints primaryKey="true" />
            </column>
            <column name="operation_id" type="varchar(37)">
                <constraints primaryKey="true" />
            </column>
        </createTable>
    </changeSet>

    <changeSet id="25" logicalFilePath="powerauth-java-server/1.4.x/20230322-init-db.xml" author="Lubos Racansky">
        <preConditions onFail="MARK_RAN">
            <not>
                <tableExists tableName="pa_operation_application"/>
            </not>
        </preConditions>
        <comment>Create a new table pa_operation_application</comment>
        <createTable tableName="pa_operation_application">
            <column name="application_id" type="bigint">
                <constraints primaryKey="true" />
            </column>
            <column name="operation_id" type="varchar(255)">
                <constraints primaryKey="true" />
            </column>
        </createTable>
    </changeSet>
```

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Review by romanstrobl — APPROVED** [review]
Looks OK. I guess we need to keep the IDs as they are.

**Review by zcgandcomp — CHANGES_REQUESTED** [review]
Sorry, we need to explain this. I do not understand the change

**Comment by banterCZ** [comment]
> Sorry, we need to explain this. I do not understand the change

@zcgandcomp As described in the issues https://github.com/wultra/powerauth-server/issues/1257, the changeset has been duplicated

**Review by zcgandcomp — APPROVED** [review]
Ok removing duplicit changeset - valid correction.

**Pull request merged**
