### PR TITLE
Fix #1306: Failing tests when Tomcat is running on port 8080

### LINKED ISSUE #1306: Failing tests when Tomcat is running on port 8080
When I run PowerAuth server on localhost on port 8080 and run the tests using Maven on the same environment, the tests fail.

Full log attached.
[Uploading log_failed_tests.txt…]()

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Review by jandusil — DISMISSED** [review]
looks okay

**Review by romanstrobl — APPROVED** [review]
Thanks for the fix.

**Review by zcgandcomp — CHANGES_REQUESTED** [review]
Please consider my comment.

**Review by jandusil — APPROVED** [review]
better, thanks

**Review by zcgandcomp — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
